### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by selam-ben-samet** [selam-ben-samet/Sky-Shooter#1]
- [ ] ADD panel ship information
- [ ] ADD pause menu in game
- [ ] ADD main menu
- [ ] EDIT death screen
- [ ] ADD sounds
- [ ] OPTIMIZE codes
- [ ] DO build settings
- [ ] EDIT game mathematics
